### ISSUE TITLE
For NHI numbers in the new format, the calculated sum modulo 23

### ISSUE THREAD

**Issue by teebu** [elilambnz/nhi-validator#158]
For NHI numbers in the new format, the calculated sum modulo 23 is subtracted from 23
to give an index number

documentation: https://www.tewhatuora.govt.nz/publications/hiso-100462023-consumer-health-identity-standard/
and https://en.wikipedia.org/wiki/NHI_Number

**Comment by elilambnz** [comment]
Thanks, fixed in `2.1.0`.
